version: "3.8"

services:
  pocketbase-chatbox:
    container_name: pocketbase-chatbox
    build:
      context: ../
      dockerfile: deploy/Dockerfile
      args:
        - POCKBASE_ADDR=https://chat.my.dev # <- change this to your domain or ip, chatbox and pocketbase sharing the same address
    restart: always
    volumes:
      - ./pb_data:/pb_data
    ports:
      - "8090:8090"
    entrypoint: /bin/sh -c
    command: >
      "/usr/local/bin/pocketbase serve --http='0.0.0.0:8090' --dir='/pb_data' --publicDir='/pb_public'"
